TITLE         = "SHADOW SIGNAL"
SCREEN_WIDTH  = 900
SCREEN_HEIGHT = 600
FPS           = 60
TILE_SIZE     = 32

# Colors
BLACK         = (0,   0,   0)
WHITE         = (255, 255, 255)
RED           = (200, 0,   0)
DARK_RED      = (100, 0,   0)
DIM_GRAY      = (20,  20,  20)
AMBER         = (255, 180, 0)
GREEN_SIGNAL  = (0,   220, 80)
DANGER_RED    = (220, 30,  30)

# Player
PLAYER_SPEED        = 160
PLAYER_SPRINT_SPEED = 280
PLAYER_CROUCH_SPEED = 70
PLAYER_MAX_HEALTH   = 100

# Flashlight
FLASHLIGHT_MAX_BATTERY  = 100.0
FLASHLIGHT_DRAIN_RATE   = 0.8
FLASHLIGHT_OVERHEAT_MAX = 100.0
FLASHLIGHT_HEAT_RATE    = 1.2
FLASHLIGHT_COOL_RATE    = 6.0
FLASHLIGHT_RADIUS       = 180

# Signal
SIGNAL_MAX          = 100.0
SIGNAL_DECAY_RATE   = 0.5
SIGNAL_CRIT_THRESH  = 25.0
SIGNAL_ZERO_THRESH  = 0.0

# Sound
SOUND_RADIUS_WALK   = 80
SOUND_RADIUS_SPRINT = 200
SOUND_RADIUS_CROUCH = 20
SOUND_RADIUS_DOOR   = 250

# Enemy
WATCHER_SPEED_DARK    = 100
WATCHER_SPEED_FLICKER = 40
WATCHER_SPEED_LIGHT   = 0
WATCHER_DETECT_RANGE  = 180
ENEMY_DRAW_RADIUS     = 18

# Game States
STATE_TITLE    = "title"
STATE_PLAYING  = "playing"
STATE_PAUSED   = "paused"
STATE_GAMEOVER = "gameover"
STATE_WIN      = "win"

# Paths
ASSET_DIR  = "assets"
SAVE_FILE  = "saves/save_data.json"